# Generated by Django 5.1.2 on 2024-11-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_game_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(verbose_name='date created')),
                ('matches_won', models.IntegerField(default=0)),
                ('matches_lost', models.IntegerField(default=0)),
            ],
        ),
    ]
