# Generated by Django 5.1.2 on 2025-02-04 13:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_won', models.IntegerField(default=0)),
                ('matches_lost', models.IntegerField(default=0)),
                ('display_name', models.CharField(default='', max_length=50)),
                ('quiz_games_played', models.IntegerField(default=0)),
                ('quiz_games_won', models.IntegerField(default=0)),
                ('quiz_total_score', models.BigIntegerField(default=0)),
                ('quiz_high_score', models.IntegerField(default=0)),
                ('quiz_questions_asked', models.IntegerField(default=0)),
                ('quiz_correct_answers', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.IntegerField(default=0)),
                ('score2', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('played_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pending', models.BooleanField(default=True)),
                ('player1_ready', models.BooleanField(default=False)),
                ('player2_ready', models.BooleanField(default=False)),
                ('player1_control_settings', models.CharField(default='up down', max_length=255)),
                ('player2_control_settings', models.CharField(default='up down', max_length=255)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player1', to='game.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player2', to='game.player')),
            ],
        ),
    ]
