# Generated by Django 5.1.2 on 2024-12-16 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_player_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='user',
        ),
    ]
