# Generated by Django 5.1.5 on 2025-02-05 00:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='', max_length=255)),
                ('player1', models.CharField(default='', max_length=255)),
                ('player2', models.CharField(default='', max_length=255)),
                ('player3', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('winner1', models.CharField(default='', max_length=255)),
                ('winner2', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
