# Generated by Django 5.1.3 on 2024-11-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_pending_alter_game_played_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player1_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_ready',
            field=models.BooleanField(default=False),
        ),
    ]
