# Generated by Django 5.1.3 on 2024-11-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_player1_ready_game_player2_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player1_control_settings',
            field=models.CharField(default='up down', max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_control_settings',
            field=models.CharField(default='up down', max_length=255),
        ),
    ]
