# Generated by Django 5.1.5 on 2025-02-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_tournement_opentournement'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournement',
            name='playernum',
            field=models.IntegerField(default=0),
        ),
    ]
