# Generated by Django 5.1.2 on 2024-12-22 19:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('game', '0008_game_pending_game_player1_ready_game_player2_ready_and_more'), ('game', '0009_game_player1_control_settings_and_more'), ('game', '0010_alter_game_player1_alter_game_player2'), ('game', '0011_alter_game_player1_alter_game_player2')]

    dependencies = [
        ('game', '0001_initial_squashed'),
        ('users', '0002_profile_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='player1_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='played_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='game',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='game',
            name='player1_control_settings',
            field=models.CharField(default='up down', max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_control_settings',
            field=models.CharField(default='up down', max_length=255),
        ),
        migrations.AlterField(
            model_name='game',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player1', to='game.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player2', to='game.player'),
        ),
    ]
