# Generated by Django 5.1.2 on 2024-12-19 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='player1_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='played_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='game',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
