# Generated by Django 5.1.2 on 2024-12-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_game_pending_game_player1_ready_game_player2_ready_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player1_control_settings',
            field=models.CharField(default='up down', max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_control_settings',
            field=models.CharField(default='up down', max_length=255),
        ),
    ]
