# Generated by Django 5.1.4 on 2025-01-07 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='current_question',
        ),
        migrations.RemoveField(
            model_name='room',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='room',
            name='shuffled_answers',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
