# Generated by Django 5.1.5 on 2025-01-17 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_room_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_count', models.PositiveSmallIntegerField(default=5)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_settings', to='quiz.room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='settings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_settings', to='quiz.roomsettings'),
        ),
    ]
