# Generated by Django 5.1.4 on 2025-01-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
