# Generated by Django 5.1.5 on 2025-01-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_roomsettings_room_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_question',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='questions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='shuffled_answers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
