# Generated by Django 5.1.4 on 2024-12-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_room_game_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_question',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='questions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='shuffled_answers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
