# Generated by Django 5.1.5 on 2025-01-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_room_current_question_room_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_ingame',
            field=models.BooleanField(default=False),
        ),
    ]
