# Generated by Django 5.1.5 on 2025-01-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_room_is_ingame'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_given',
            field=models.JSONField(default=dict),
        ),
    ]
