# Generated by Django 5.1.4 on 2025-01-07 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='room',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='room',
            name='leader',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
