# Generated by Django 5.1.5 on 2025-01-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_answer_question_alter_answer_answer_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsettings',
            name='time_after_game_end',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='roomsettings',
            name='time_after_question',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='roomsettings',
            name='time_per_qestion',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
