# Generated by Django 5.1.5 on 2025-01-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_roomsettings_time_after_game_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_disqualified',
            field=models.BooleanField(default=False),
        ),
    ]
