# Generated by Django 5.1.5 on 2025-01-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_answer_is_disqualified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_given',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
