# Generated by Django 5.1.5 on 2025-01-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_answer_answer_given_alter_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
