# Generated by Django 5.1.5 on 2025-01-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_participant_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='question_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
