# Generated by Django 5.1.5 on 2025-01-23 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_room_question_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomsettings',
            old_name='time_per_qestion',
            new_name='time_per_question',
        ),
    ]
