# Generated by Django 5.1.5 on 2025-01-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_rename_time_per_qestion_roomsettings_time_per_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsettings',
            name='difficulty',
            field=models.CharField(default='any', max_length=10),
        ),
    ]
