# Generated by Django 5.1.5 on 2025-01-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_roomsettings_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='score_difference',
            field=models.IntegerField(default=0),
        ),
    ]
