# Generated by Django 5.1.5 on 2025-01-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_participant_score_difference'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsettings',
            name='categorie',
            field=models.CharField(default='any', max_length=60),
        ),
    ]
