# Generated by Django 5.1.5 on 2025-01-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_roomsettings_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsettings',
            name='categorie',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
