# Generated by Django 5.1.5 on 2025-01-28 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_alter_roomsettings_categorie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomsettings',
            old_name='categorie',
            new_name='category',
        ),
    ]
