# Generated by Django 5.1.5 on 2025-02-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pong_games_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='pong_games_won',
            field=models.IntegerField(default=0),
        ),
    ]
