# Generated by Django 5.1.5 on 2025-02-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='quiz_correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='quiz_games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='quiz_games_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='quiz_high_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='quiz_questions_asked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='quiz_total_score',
            field=models.BigIntegerField(default=0),
        ),
    ]
