# Generated by Django 5.1.2 on 2025-01-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_friends_manager_friends'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friends_Manager',
        ),
        migrations.AddField(
            model_name='friends',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
